spring:
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27017/user_storage?authSource=admin
      authentication-database: admin
      auto-index-creation: true
  application:
    name: user
server:
  port: 8080