server:
  port: 9100

spring:
  application:
    name: jtax-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/h1alexbel/config-server
          clone-on-start: true